
INSERT INTO TIPO_CONTRATO VALUES(1,'Manutenção');

INSERT INTO TIPO_CONTRATO VALUES(2,'Manutenção de Sistema Operacional');

INSERT INTO TIPO_CONTRATO VALUES(3,'Treinamento');

INSERT INTO TIPO_CONTRATO VALUES(4,'-');

INSERT INTO TIPO_CONTRATO VALUES(5,'-');

INSERT INTO TIPO_CONTRATO VALUES(6,'-');

INSERT INTO TIPO_CONTRATO VALUES(7,'-');

INSERT INTO TIPO_CONTRATO VALUES(8,'-');

INSERT INTO TIPO_CONTRATO VALUES(9,'-');

INSERT INTO TIPO_CONTRATO VALUES(10,'-');

